### ISSUE TITLE
Limit of 7 notes?

### ISSUE THREAD

**Issue by comatose-tortoise** [rpggio/obsidian-chat-stream#1]
There appears to be a limit of 7 notes being sent to GPT, but I can't see this mentioned anywhere in the docs?

**Comment by hodgea** [comment]
Increase your max input characters in the settings and it should work with more than 7.

**Comment by comatose-tortoise** [comment]
I have it set to 7800 tokens, but when it reaches 7 notes it doesn't add more to the prompt, regardless of note size, nb.

**Comment by rpggio** [comment]
Yes, it is an arbitrary limit. I'll make it a setting and make the default to be unlimited.

**Comment by comatose-tortoise** [comment]
Thanks!

**Comment by rpggio** [comment]
Fixed in [1.1.0](https://github.com/rpggio/obsidian-chat-stream/releases/tag/1.1.0)

**Comment by comatose-tortoise** [comment]
Works perfectly! If you're taking requests, it would be great to have it either:

1: Display the number of tokens sent in each call
or
2: Let the user know (maybe with an auto-added text in the current box?) that the prompt exceeded the total token limit

Or both would be great, too.

**Comment by rpggio** [comment]
Glad to hear it!
I haven't really been testing for longer prompts. I'll check it out.
I'm interested to know what you're using it for. I generally use it for
brainstorming and problem solving.

**Comment by comatose-tortoise** [comment]
OpenAI has a model where you can send the prompt to get number of tokens back, have a look at it. Probably not a good idea to do that first and wait for the answer. Getting a token notification after the response is printed is fine.

What I'm after is just to get some idea about where I am compared to the limit, or when I past it and it starts ignoring the notes in the beginning.

I'm only just trying it out, but essentially the same way as with any OpenAI API chat interface. It's just that when you have visual "threads" like this, it's easier to get an overview and also to "branch out" from a certain point, instead of creating a new chat and input the same stuff again.

**Comment by rpggio** [comment]
@comatose-tortoise better late than never: Chat Stream [now uses all tokens available](https://github.com/rpggio/obsidian-chat-stream/releases/tag/1.4.3), and prints the token usage when you generate. Thanks for the input!

**Comment by comatose-tortoise** [comment]
Thank you, works splendidly!
