### ISSUE TITLE
Feature Request: Read information from embeds

### ISSUE THREAD

**Issue by wwboynton** [rpggio/obsidian-chat-stream#12]
Chat stream does a bang-up job of reading information from notes added to a canvas. However, sometimes canvases are put together with references to just one section of a note, by creating a card and referencing the section like this:

```
![[My Cool Note#Chapter 1]]
```

Within the canvas, this has the effect of rendering that part of the note in the card. However, it seems Chat Stream doesn't have any current way of resolving those details, so they're quietly left out of the context handed to the LLM. It would be neat if these links within cards were supported.

**Comment by rpggio** [comment]
Fixed in [1.4.3](https://github.com/rpggio/obsidian-chat-stream/releases/tag/1.4.3). Thanks for the request!
