### ISSUE TITLE
[minor] typo in settings tab. "Max pesponse tokens" -> "Max response tokens"

### ISSUE THREAD

**Issue by blakejwc** [rpggio/obsidian-chat-stream#2]
https://github.com/rpggio/obsidian-chat-stream/blob/7d32ea4d5d919287f1c9888f58a9eb7afa70582e/src/settings/SettingsTab.ts#L77

Small typo in the name of the setting for providing the maximum number of response tokens. I believe "pesponse" should be "response".

**Comment by rpggio** [comment]
Thanks! Will be in next release.

**Comment by rpggio** [comment]
Fixed in 1.3.1
