### ISSUE TITLE
Support for GPT-4 Turbo with Image as encode files

### ISSUE THREAD

**Issue by vratclarkson** [rpggio/obsidian-chat-stream#27]
Hello @rpggio , @jshph  and @bitnom 

Thank you for developing this plugin.

I am opening this issue to request a feature for `gpt-4-turbo` model along with some support to ask questions on images that are on the canvas. 

This would greatly be helpful to ask question on graphs, equation, etc. To give full context to the model. 

https://platform.openai.com/docs/guides/vision

Thank you once again

**Comment by rpggio** [comment]
Props to @blaulan 👏 
https://github.com/rpggio/obsidian-chat-stream/releases/tag/1.4.7
