### ISSUE TITLE
Editing will be interrupted while ChatGPT completes the content of a card

### ISSUE THREAD

**Issue by hongxunming** [rpggio/obsidian-chat-stream#4]
Thank you very much for your work; this plugin has brought me great convenience!!

After using the "Chat Stream: Generate AI note" function, the newly generated card will display "Calling GPT (gpt-4)…". At that moment, when I go to edit other cards, if ChatGPT has generated the complete content, I will be forced out of the edit mode. This means that every time ChatGPT completes the content of a card, my editing is interrupted. Is it possible not to be forced out of the edit mode?

**Comment by rpggio** [comment]
Hi @hongxunming , thanks for letting me know it is useful! I don't have it instrumented for usage metrics yet.

The [latest release](https://github.com/rpggio/obsidian-chat-stream/releases/tag/1.3.1) should fix this. If you are editing a different node, it should leave the focus alone when generation is complete.

**Comment by hongxunming** [comment]
Thanks!!!
