### ISSUE TITLE
Feature request: Support 'Zoom Out to Title'

### ISSUE THREAD

**Issue by 541864509proton** [rpggio/obsidian-chat-stream#9]
When I add a note containing multiple"h1”titles in "canvas", select "Zoom Out to Title" from the right-click menu option, choose to display only one"h1”title, and use "Alt+Shift+G" to start running. As a result, the chat stream plugin still sent the entire note content to chatgp. According to the "Zoom Out to Title" display, users should see information with only one"h1”title, and the information sent to chatgp should only contain the content of this"h1”title, rather than the entire note content. This makes users very troubled. I hope to improve this bug. But we still need to appreciate it 👍 The 'chat stream' you developed unleashed my natural thinking ability 😊

**Comment by rpggio** [comment]
OK, we can add a setting to only send the visible title from notes if the note is collapsed.

**Comment by 541864509proton** [comment]
I am glad that you have taken this issue seriously. 😊 The 'chat stream' has stimulated my potential for thinking. 🚀 By quickly switching between the types of titles that need to be displayed through 'Zoom Out to Title', such as H1/H2/H3/H4/H5/H6, it can significantly improve the efficiency of note utilization. 📚 There is no need to create a new note for a thought process. Just a note containing complete information, quickly assemble prompt words through "Zoom Out to Title", and send it to chatgp to help me think completely. 💭

**Comment by rpggio** [comment]
@541864509proton I do not see option 'Zoom Out to Title'. Maybe this is from another plugin?

I am, however, [adding support](https://github.com/rpggio/obsidian-chat-stream/issues/12) Narrow to Heading and Narrow to Block. Will this work for your use case, to include just the heading or file block you wish to use?
![image](https://github.com/rpggio/obsidian-chat-stream/assets/5432713/cdf18aa7-21c2-45d6-885b-99a693f2e896)

If this is not adequate for your use case, please locate the plugin or the Obsidian docs which will show me where to find 'Zoom Out to Title'.

**Comment by rpggio** [comment]
'Narrow to heading' and 'Narrow to block' are supported in the latest release.

**Comment by linxizhiri** [comment]
I am a user of "541864509proton".😊 I am very glad that you have found the entrance of "Narrow to heading, Narrow to Block" and implemented this function.This is a great initiative that has further enhanced the power of this plugin.👍
Recently, a plugin called "cannoli" has been discovered, which also uses "canvas" to structure thinking, create and run LLM scripts.It is similar to your plugin.When the two are combined, they will create a more brilliant spark.🚀

**Comment by rpggio** [comment]
Thanks @linxizhiri, will def. check out cannoli.
